# Generated by Django 5.2 on 2025-04-10 23:19

import api.models.organisation
import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField()),
                ('partner_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PRESENTER', 'Presenter'), ('INFORMATION_MARKET', 'Information Market'), ('DIGITAL', 'Digital Partner')], max_length=36, null=True)),
                ('logo', models.ImageField(upload_to='', validators=[api.models.organisation.validate_minimum_size, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=35)),
                ('preposition_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(max_length=35)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('study_phase', models.CharField(max_length=25)),
                ('study', models.CharField(max_length=25)),
                ('study_year', models.CharField(max_length=25)),
                ('dietary_requirements', models.CharField(blank=True, max_length=25, null=True)),
                ('membership_id', models.IntegerField(unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_session', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(max_length=20)),
                ('max_attendance', models.IntegerField(default=40)),
                ('is_registrable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.organisation')),
                ('time_slot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='SessionRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='session_participants', to='api.participant')),
                ('session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
    ]
