# Generated by Django 5.2 on 2025-04-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionregistration',
            options={'ordering': ['-registered_at']},
        ),
    ]
