# Generated by Django 5.2 on 2025-04-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='body_html',
            new_name='body',
        ),
    ]
