# Generated by Django 5.2 on 2025-04-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_body_html_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='emails/'),
        ),
    ]
