# Generated by Django 5.2 on 2025-04-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_email_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
