# Generated by Django 5.2 on 2025-04-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionregistration',
            options={'ordering': ['-session__time_slot__start_time']},
        ),
    ]
