# Generated by Django 5.2 on 2025-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sessionregistration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='membership_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
