# Generated by Django 5.2 on 2025-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_participant_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='membership_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
