# Generated by Django 5.2 on 2025-04-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_participant_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.organisation'),
        ),
    ]
