import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import Partners from './components/Partners';

export const metadata: Metadata = {
  title: "Cover Career Day",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
        <nav>
            <Navbar />
        </nav>
        {children}
        <footer>
            <Partners />
            <Footer />
        </footer>
        </body>
    </html>
  );
}
