services:
  backend:
    build:
      context: ./backend
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app


  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: careerday
      POSTGRES_USER: careeruser
      POSTGRES_PASSWORD: yourpassword

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data: